import jax
import jax.numpy as jnp
import optax
import flax.linen as nn
from flax.training import train_state
from typing import Any, Tuple, Dict
from functools import partial
from src.models_jax import MLP

class VAE(nn.Module):
    """VAE to model the distribution of actions in the batch."""
    hidden_dims: Tuple[int, ...]
    latent_dim: int
    action_dim: int

    @nn.compact
    def __call__(self, obs, action=None):
        # Encoder
        x = jnp.concatenate([obs, action], axis=-1)
        x = MLP(self.hidden_dims)(x)
        mu = nn.Dense(self.latent_dim)(x)
        log_var = nn.Dense(self.latent_dim)(x)
        
        # Decoder (Generation)
        def decode(z, o):
            y = jnp.concatenate([o, z], axis=-1)
            y = MLP(self.hidden_dims)(y)
            return nn.sigmoid(nn.Dense(self.action_dim)(y))
        
        return mu, log_var, decode

    def generate(self, obs, z):
        x = jnp.concatenate([obs, z], axis=-1)
        x = MLP(self.hidden_dims)(x)
        return nn.sigmoid(nn.Dense(self.action_dim)(x))

class BCQCritic(nn.Module):
    hidden_dims: Tuple[int, ...]
    @nn.compact
    def __call__(self, obs, action):
        x = jnp.concatenate([obs, action], axis=-1)
        q1 = MLP(self.hidden_dims + (1,))(x)
        q2 = MLP(self.hidden_dims + (1,))(x)
        return q1, q2

class PerturbationNet(nn.Module):
    hidden_dims: Tuple[int, ...]
    action_dim: int
    phi: float = 0.05
    
    @nn.compact
    def __call__(self, obs, action):
        x = jnp.concatenate([obs, action], axis=-1)
        x = MLP(self.hidden_dims)(x)
        delta = nn.Dense(self.action_dim)(x)
        delta = nn.tanh(delta) * self.phi
        return jnp.clip(action + delta, 0.0, 1.0)

@partial(jax.jit, static_argnums=(0,))
def _update_bcq_jit(agent, vae_state, critic_state, perturb_state, target_critic_params, target_perturb_params, batch, key):
    obs, actions, rewards, next_obs, masks = (
        batch['observations'], batch['actions'], batch['rewards'], 
        batch['next_observations'], batch['masks']
    )
    
    # 1. VAE Update
    def vae_loss_fn(v_params):
        mu, log_var, decode_fn = vae_state.apply_fn({'params': v_params}, obs, actions)
        std = jnp.exp(0.5 * log_var)
        z = mu + std * jax.random.normal(key, mu.shape)
        recon_a = decode_fn(z, obs)
        
        recon_loss = ((recon_a - actions)**2).mean()
        kl_loss = -0.5 * jnp.mean(1 + log_var - mu**2 - jnp.exp(log_var))
        return recon_loss + 0.5 * kl_loss

    v_loss, v_grads = jax.value_and_grad(vae_loss_fn)(vae_state.params)
    vae_state = vae_state.apply_gradients(grads=v_grads)

    # 2. Critic Update
    def critic_loss_fn(c_params):
        q1, q2 = critic_state.apply_fn({'params': c_params}, obs, actions)
        
        # Sample next actions from VAE + Perturb
        # We sample 10 actions and take the one with highest Q (BCQ trick)
        z_next = jax.random.normal(key, (next_obs.shape[0], 10, 1)) # latent_dim=1
        
        # Broadcast next_obs: (batch, 1, dim) -> (batch, 10, dim)
        next_obs_tiled = jnp.tile(jnp.expand_dims(next_obs, 1), (1, 10, 1))
        
        # This part is complex in JIT, we simplify by generating and perturbing
        # In a real BCQ we'd use a specific method from VAE
        # For simplicity in this port:
        next_actions = vae_state.apply_fn({'params': vae_state.params}, next_obs_tiled, method=VAE.generate, z=z_next)
        next_actions = perturb_state.apply_fn({'params': target_perturb_params}, next_obs_tiled, next_actions)
        
        # Evaluate all 10 actions
        q1_t, q2_t = critic_state.apply_fn({'params': target_critic_params}, next_obs_tiled, next_actions)
        target_q = rewards + agent.discount * masks * (0.75 * jnp.minimum(q1_t, q2_t).max(axis=1) + 0.25 * jnp.maximum(q1_t, q2_t).max(axis=1))
        
        return ((q1 - target_q)**2 + (q2 - target_q)**2).mean()

    q_loss, q_grads = jax.value_and_grad(critic_loss_fn)(critic_state.params)
    critic_state = critic_state.apply_gradients(grads=q_grads)

    # 3. Perturbation (Actor) Update
    def perturb_loss_fn(p_params):
        # We want to maximize Q for the actions generated by VAE
        z = jax.random.normal(key, (obs.shape[0], 1, 1))
        a = vae_state.apply_fn({'params': vae_state.params}, obs, method=VAE.generate, z=z)
        a_perturbed = perturb_state.apply_fn({'params': p_params}, obs, a)
        q1, _ = critic_state.apply_fn({'params': critic_state.params}, obs, a_perturbed)
        return -q1.mean()

    p_loss, p_grads = jax.value_and_grad(perturb_loss_fn)(perturb_state.params)
    perturb_state = perturb_state.apply_gradients(grads=p_grads)

    # 4. Target Updates
    new_target_critic = optax.incremental_update(critic_state.params, target_critic_params, agent.target_update_rate)
    new_target_perturb = optax.incremental_update(perturb_state.params, target_perturb_params, agent.target_update_rate)

    return vae_state, critic_state, perturb_state, new_target_critic, new_target_perturb, {"q_loss": q_loss}

class BCQAgent:
    def __init__(self, observation_dim: int, action_dim: int, seed: int = 42):
        self.discount = 0.99
        self.target_update_rate = 0.005
        self.n_devices = jax.local_device_count()
        
        key = jax.random.PRNGKey(seed)
        vae_def = VAE(hidden_dims=(256, 256), latent_dim=1, action_dim=action_dim)
        critic_def = BCQCritic(hidden_dims=(256, 256))
        perturb_def = PerturbationNet(hidden_dims=(256, 256), action_dim=action_dim)
        
        key, v_key, c_key, p_key = jax.random.split(key, 4)
        obs_dummy = jnp.zeros((1, observation_dim))
        act_dummy = jnp.zeros((1, action_dim))

        self.vae_state = train_state.TrainState.create(apply_fn=vae_def.apply, params=vae_def.init(v_key, obs_dummy, act_dummy)['params'], tx=optax.adam(3e-4))
        self.critic_state = train_state.TrainState.create(apply_fn=critic_def.apply, params=critic_def.init(c_key, obs_dummy, act_dummy)['params'], tx=optax.adam(3e-4))
        self.target_critic_params = self.critic_state.params
        self.perturb_state = train_state.TrainState.create(apply_fn=perturb_def.apply, params=perturb_def.init(p_key, obs_dummy, act_dummy)['params'], tx=optax.adam(3e-4))
        self.target_perturb_params = self.perturb_state.params
        self.key = key

    def update(self, batch):
        self.key, update_key = jax.random.split(self.key)
        self.vae_state, self.critic_state, self.perturb_state, self.target_critic_params, self.target_perturb_params, metrics = \
            _update_bcq_jit(self, self.vae_state, self.critic_state, self.perturb_state, self.target_critic_params, self.target_perturb_params, batch, update_key)
        return metrics

    def select_action(self, observations):
        # For BCQ, we sample 100 actions from VAE and pick the one with highest Q
        key, subkey = jax.random.split(self.key)
        z = jax.random.normal(subkey, (observations.shape[0], 100, 1))
        obs_tiled = jnp.tile(jnp.expand_dims(observations, 1), (1, 100, 1))
        actions = self.vae_state.apply_fn({'params': self.vae_state.params}, obs_tiled, method=VAE.generate, z=z)
        actions = self.perturb_state.apply_fn({'params': self.perturb_state.params}, obs_tiled, actions)
        q1, _ = self.critic_state.apply_fn({'params': self.critic_state.params}, obs_tiled, actions)
        idx = q1.argmax(axis=1)
        # Use jnp.take_along_axis to pick the best action
        return jnp.take_along_axis(actions, jnp.expand_dims(idx, (1, 2)), axis=1).squeeze(1)
