experiment_name: "exp_benchmark"

env:
  horizon: 128
  execution_capacity: 100
  arrival_scale: 0.1
  safety_ratio: 0.2
  C_base: 21000
  C_mar: 15000

state:
  num_lags: 5

rl:
  algorithms: ["cql", "iql", "td3_bc", "awac", "bcq"]
  gamma: 0.99
  urgency_beta: 100.0
  urgency_alpha: 3.0
  deadline_penalty: 5000000000.0
  iql_expectile: 0.7
  iql_beta: 3.0
  cql_alpha: 1.0
  td3_bc_alpha: 2.5
  awac_beta: 1.0
  bcq_phi: 0.05
